## Numpy


### Was ist NumPy?
* Erstellen von N-dimensionalen Arrays (1D, 2D, 3D, ..., n-D)
* Eingebaute Funktionen für lineare Algebra, Trigonometrie, Zufallszahlen, ....
* Fast jede der folgenden Libraries ist auf NumPy aufgebaut
* Wichtig: NumPy muss gegen numerische Bibliothek gelinkt sein um volle Thread-Parallelisierung zu gewährleisten.

### Erstellen von NumPy Arrays



#### Transformieren einer Python-Liste zu einem NumPy Array:

In [ ]:
import numpy as np
list = [1,2,3]
type(list)

list

In [ ]:
np.array(list)

array([1, 2, 3])

In [ ]:
list

[1, 2, 3]

In [ ]:
array = np.array(list)
type(array)

numpy.ndarray

#### Verschachtelte Listen:

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

NumPy erkennt 2D Array automatisch.

#### Erstellen von neuem NumPy Array:

In [ ]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

---
3 Zahlen zwischen 0 und 10 mit gleichem Abstand:

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

---
Einheitsmatrix:

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---
Zufallsmatrizen:

Uniform Distribution [0,1): Alle Zahlen zwischen 0 und 1 haben die gleiche Wahrscheinlichkeit gewaehlt zu werden

In [ ]:
np.random.rand(1)

array([0.32986464])

In [ ]:
np.random.rand(5,2)

array([[0.53284345, 0.02459899],
       [0.16548164, 0.10980854],
       [0.80638967, 0.13708751],
       [0.17646341, 0.32232707],
       [0.33402728, 0.5088892 ]])

---
Standardnormalverteilung: Median ist 0 und Varianz ist 1

In [ ]:
np.random.randn(2,3)

array([[-0.39037377, -0.27463874, -0.41623287],
       [ 0.29202229, -0.29571762,  0.87155655]])

---

In [ ]:
np.random.randint(0,101,(4,5))

array([[ 0, 30, 58, 98, 63],
       [35,  6, 50, 24, 81],
       [12, 45, 29, 23, 73],
       [14, 73, 54, 54, 88]])

---
Reproduzierbare Zufallszahlen:

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

---
Reshaping:

In [ ]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

---
Maxima und Minima finden:

In [ ]:
arr = np.random.randint(0,101,10)

In [ ]:
arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [ ]:
arr.max()

99

In [ ]:
arr.argmax()

5

In [ ]:
arr.min()

2

In [ ]:
arr.dtype

dtype('int64')

### NumPy Indexing und Selection

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---
Broadcasting:
* Nicht moeglich mit Standard Python Listen

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

---
Slicing:

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 42
slice_of_arr

array([42, 42, 42, 42, 42])

In [ ]:
arr ## Original arr wurde durch Broadcast von sclice_of_arr ueberschrieben....

array([42, 42, 42, 42, 42,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy() ## copy() kann hier Abhilfe beschaffen
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([42, 42, 42, 42, 42,  5,  6,  7,  8,  9, 10])

---
Multi dimensional Arrays:


In [ ]:
arr_2d = np.array([[1,2,3],[20,5,6],[8,4,3]])
arr_2d

array([[ 1,  2,  3],
       [20,  5,  6],
       [ 8,  4,  3]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
arr_2d[2]

array([8, 4, 3])

In [ ]:
arr_2d[1][1]

5

In [ ]:
arr_2d[1,1]

5

In [ ]:
arr_2d[:2]

array([[ 1,  2,  3],
       [20,  5,  6]])

In [ ]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

---
Boolean Array:


In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

### NumPy Operationen

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr / arr

/tmp/ipykernel_380331/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.sum()

45

In [ ]:
arr.max()

9

In [ ]:
arr.var()

8.25

In [ ]:
arr.std()

2.8722813232690143

### Aufgaben