<img src="../../images/bwHPC_Logo_cmyk.svg" width="200" /> <img src="../../images/HochschuleEsslingen_Logo_RGB_DE.png" width="200" /> <img src="../../images/Konstanz_Logo.svg" width="200" /> <img src="../../images/KIT_Logo.png" width="200" />

# Introduction to Supervised Learning

**Machine learning** algorithms use statistics to find patterns in large amounts of
data, and then use those patterns to make predictions. Assessing creditworthiness,
forecasting prices, filtering spam — all of them work the same way: show the
algorithm enough past examples, and it works out the rule for itself.

The quality of those predictions depends above all on the quality of the data.

This chapter is split in two, and the split follows the most important distinction
in machine learning:

- **`01_Supervised_Learning`** — this folder. The past data comes with the answers
  attached, and the algorithm learns to reproduce them.
- **`02_Unsupervised_Learning`** — the other folder. There are no answers, and the
  algorithm has to find structure in the data on its own.

This notebook introduces the vocabulary and the workflow that the rest of this
folder relies on. We deliberately use a tiny, artificial dataset here, so that
nothing distracts from the four steps every supervised model goes through.

---

## Contents

1. [Supervised and unsupervised learning](#kinds)
2. [Features and labels](#xy)
3. [Training data and test data](#split)
4. [scikit-learn](#sklearn)
5. [The workflow, step by step](#workflow)
6. [Why the amount of training data matters](#size)

<a id="kinds"></a>
## 1. Supervised and unsupervised learning

**Supervised learning** works from past data where *the desired output is already
known*. For a set of taxi rides we know the hour, the number of passengers, the
distance — and we also know what each ride actually cost. Data like this is called
**labelled**, and the label is the answer we want the model to reproduce for rides
it has never seen.

Supervised problems come in two kinds, and the difference is simply what sort of
answer you are after:

| Kind | The label is | Example |
|---|---|---|
| **Regression** | a continuous number | the fare of a taxi ride, the price of a house |
| **Classification** | one of a few fixed categories | handwriting recognition, spam or not spam |

**Unsupervised learning** is the case where no labels exist at all. Nobody has said
what the right answer is, so the algorithm has to find structure by itself — for
instance by discovering that the data falls into groups. That is the subject of the
`02_Unsupervised_Learning` folder; everything here is supervised.

<a id="xy"></a>
## 2. Features and labels

Two letters appear in essentially every machine learning example, including all the
notebooks in this chapter:

- **`X`** — the **features**: the data used to make the estimate
- **`y`** — the **label**: the value we want to predict

For taxi rides, `X` would hold the hour, the passenger count and the distance, while
`y` holds the fare.

<a id="split"></a>
## 3. Training data and test data

A model that has memorised its examples will answer them perfectly and still be
useless. To find out whether it has learned anything that *generalises*, part of the
data is held back: the model is trained on one part and checked against the other,
which it has never seen.

Say we have nine taxi rides. Six of them are given to the model to learn from — it
sees the three features *and* the fare that each ride actually cost:

**Training data**

| Hour | # Passengers | Distance travelled | Fare (USD) |
|------|--------------|--------------------|-----------:|
| 23   | 5            | 10                 | 10         |
| 22   | 3            | 14                 | 11         |
| 20   | 2            | 17                 | 15         |
| 18   | 1            | 5                  | 8          |
| 13   | 1            | 4                  | 6          |
| 15   | 4            | 43                 | 43         |

The other three are kept back. The model is shown only the first three columns and
has to produce the fourth itself. We know what it should be — that is how we can
grade the answer — but the model never saw these rides while learning:

**Test data**

| Hour | # Passengers | Distance travelled | Fare (USD) |
|------|--------------|--------------------|-----------:|
| 16   | 1            | 22                 | 27         |
| 12   | 2            | 1                  | 3          |
| 09   | 3            | 8                  | 8          |

That gives the four names used throughout: **`X_train`** and **`y_train`** to learn
from, **`X_test`** and **`y_test`** to be judged on.

<a id="sklearn"></a>
## 4. scikit-learn

**scikit-learn** is the standard Python library for classical machine learning. Its
main virtue is uniformity: every algorithm it offers is used through the same few
method calls, so swapping one model for another is a one-line change. It also brings
the tools for splitting data, validating models and comparing them, and it is
exceptionally well documented.

That uniform interface is what the rest of this notebook is really about.

<a id="workflow"></a>
## 5. The workflow, step by step

Every supervised model in scikit-learn follows the same four steps:

1. **split** the data into training and test parts
2. **fit** the model on the training part
3. **predict** the labels of the test part
4. **score** those predictions against the labels we kept back

We walk through them on a deliberately tiny dataset — six rows, two features — so
that every intermediate result fits on screen.

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.arange(12).reshape((6, 2))    # 6 rows, 2 features
y = np.arange(6)                     # the label of each row

X

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [2]:
y

array([0, 1, 2, 3, 4, 5])

Be aware of what this data is: `y` is simply the row number, and `X` counts upwards
in step with it. The relationship is exact, so any model will find it immediately.
That is deliberate — the point here is the mechanics, not the difficulty.

`train_test_split` shuffles the rows and cuts them in two. Without arguments it
keeps 25% for testing.

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print("training rows:", len(X_train))
print("test rows:    ", len(X_test))

training rows: 4
test rows:     2


Four rows to learn from, two to be tested on. The proportion is adjustable —
`test_size=0.5` splits the six rows evenly.

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)

print("training rows:", len(X_train))
print("test rows:    ", len(X_test))

training rows: 3
test rows:     3


Now the model itself. Importing it, creating it and training it are three lines —
and the same three lines, with a different name on the first, would train any other
scikit-learn model.

In [5]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](2,)","[0.25,0.25]"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-0.25
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,2
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(1)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](2,)","[8.33,0. ]"


`predict` applies the trained model to data it has not seen.

In [6]:
predictions = model.predict(X_test)

predictions

array([5., 2., 1.])

And `mean_squared_error` compares those predictions with the labels we held back.
It averages the squared difference between them, so **0 means perfect** and larger
is worse.

In [7]:
from sklearn.metrics import mean_squared_error

print("true labels:", y_test)
print("predicted:  ", predictions.round(3))
print()
print("mean squared error:", mean_squared_error(y_test, predictions))

true labels: [5 2 1]
predicted:   [5. 2. 1.]

mean squared error: 0.0


Essentially zero — but as warned above, that is a property of the data rather than
an achievement of the model. `y` was the row index and `X` counted along with it, so
there was a perfect straight line to find.

Real data never looks like this. [Notebook 02](02_Linear_Regression.ipynb) runs the
same four steps on 1000 real taxi rides, and the result is far less flattering.

<a id="size"></a>
## 6. Why the amount of training data matters

One more thing this toy example can show. Here is the identical procedure on a
dataset of **two rows** — after the split, the model has exactly one example to
learn from.

In [8]:
X = np.arange(4).reshape((2, 2))
y = np.arange(2)

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

print("training rows:", len(X_train))
print("test rows:    ", len(X_test))

training rows: 1
test rows:     1


In [9]:
model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("true label:", y_test)
print("predicted: ", predictions.round(3))
print()
print("mean squared error:", mean_squared_error(y_test, predictions))

true label: [1]
predicted:  [0.]

mean squared error: 1.0


The error jumps from almost 0 to **1.0**, on data with exactly the same structure.
Nothing about the problem changed — only the number of examples the model was
allowed to see.

This is the single most reliable lesson in machine learning: *more and better data
beats almost any amount of cleverness in the choice of model.*